from __future__ import annotations
from typing import Protocol
class EmailSender(Protocol):
    def validate_connection(self) -> None: ...
    def send(self, *, to_email: str, subject: str, body: str, from_email: str, message_id: str, in_reply_to: str|None = None) -> str: ...
    def classify_error(self, exc: Exception) -> str: ...
    def close(self) -> None: ...
